<?php

/**
 * This is the model base class for the table "mensagem".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Mensagem".
 *
 * Columns in table "mensagem" available as properties of the model,
 * followed by relations of table "mensagem" available as properties of the model.
 *
 * @property integer $idmensagem
 * @property string $mensagem
 * @property string $datahora
 * @property integer $usuario_idusuario
 *
 * @property Usuario $usuarioIdusuario
 */
abstract class BaseMensagem extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'mensagem';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Mensagem|Mensagems', $n);
	}

	public static function representingColumn() {
		return 'mensagem';
	}

	public function rules() {
		return array(
			array('usuario_idusuario', 'required'),
			array('usuario_idusuario', 'numerical', 'integerOnly'=>true),
			array('mensagem', 'length', 'max'=>45),
			array('datahora', 'safe'),
			array('mensagem, datahora', 'default', 'setOnEmpty' => true, 'value' => null),
			array('idmensagem, mensagem, datahora, usuario_idusuario', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'usuarioIdusuario' => array(self::BELONGS_TO, 'Usuario', 'usuario_idusuario'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'idmensagem' => Yii::t('app', 'Idmensagem'),
			'mensagem' => Yii::t('app', 'Mensagem'),
			'datahora' => Yii::t('app', 'Datahora'),
			'usuario_idusuario' => null,
			'usuarioIdusuario' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('idmensagem', $this->idmensagem);
		$criteria->compare('mensagem', $this->mensagem, true);
		$criteria->compare('datahora', $this->datahora, true);
		$criteria->compare('usuario_idusuario', $this->usuario_idusuario);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}