<?php

/**
 * This is the model base class for the table "usuario".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Usuario".
 *
 * Columns in table "usuario" available as properties of the model,
 * followed by relations of table "usuario" available as properties of the model.
 *
 * @property integer $idusuario
 * @property string $nome
 * @property string $ultimaconexao
 *
 * @property Mensagem[] $mensagems
 */
abstract class BaseUsuario extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'usuario';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Usuario|Usuarios', $n);
	}

	public static function representingColumn() {
		return 'nome';
	}

	public function rules() {
		return array(
			array('nome', 'required'),
			array('nome', 'length', 'max'=>45),
			array('ultimaconexao', 'safe'),
			array('ultimaconexao', 'default', 'setOnEmpty' => true, 'value' => null),
			array('idusuario, nome, ultimaconexao', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'mensagems' => array(self::HAS_MANY, 'Mensagem', 'usuario_idusuario'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'idusuario' => Yii::t('app', 'Idusuario'),
			'nome' => Yii::t('app', 'Nome'),
			'ultimaconexao' => Yii::t('app', 'Ultimaconexao'),
			'mensagems' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('idusuario', $this->idusuario);
		$criteria->compare('nome', $this->nome, true);
		$criteria->compare('ultimaconexao', $this->ultimaconexao, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}